import type { Report } from "./types";

export const mockReports: Report[] = [
  {
    id: "rep-001",
    reportCode: "RPT-20260429-001",
    title: "수원IC 주행차로 정차 신고 영상",
    reportType: "LANE_STOP_REPORT",
    purpose: "REPORT",
    reporter: "김관제",
    location: "경부고속도로 수원IC",
    cctvId: "cctv-001",
    analysisStatus: "COMPLETED",
    status: "CONVERTED_TO_INCIDENT",
    priority: "URGENT",
    createdAt: "2026-04-29 09:20:00",
    attachmentName: "suwon_lane_stop.mp4",
    attachmentType: "video",
    uploadedAt: "2026-04-29 09:19:43",
    roadName: "경부고속도로",
    locationName: "수원IC",
    convertedIncidentCode: "STP-20260429-001",
    analysisSummary: "주행차로 내 정차 차량이 70초 이상 지속되어 긴급 사고로 전환되었습니다.",
  },
  {
    id: "rep-002",
    reportCode: "RPT-20260429-002",
    title: "서해안선 갓길 장기 정차 의심",
    reportType: "SHOULDER_STOP_REPORT",
    purpose: "REPORT",
    reporter: "박운영",
    location: "서해안고속도로 안산IC",
    cctvId: "cctv-002",
    analysisStatus: "ANALYZING",
    status: "ANALYZING",
    priority: "HIGH",
    createdAt: "2026-04-29 09:42:00",
    attachmentName: "ansan_shoulder_stop.jpg",
    attachmentType: "image",
    uploadedAt: "2026-04-29 09:41:31",
    roadName: "서해안고속도로",
    locationName: "안산IC",
    analysisSummary: "갓길 영역 내 장기 정차 가능성을 분석 중입니다.",
  },
  {
    id: "rep-003",
    reportCode: "RPT-20260429-003",
    title: "영동선 이상 정체 영상 등록",
    reportType: "UNKNOWN_REPORT",
    purpose: "REPORT",
    reporter: "이상황",
    location: "영동고속도로 강릉JC",
    cctvId: "cctv-003",
    analysisStatus: "REQUESTED",
    status: "REVIEWING",
    priority: "MEDIUM",
    createdAt: "2026-04-29 10:05:00",
    attachmentName: "gangneung_unknown.mp4",
    attachmentType: "video",
    uploadedAt: "2026-04-29 10:04:22",
    roadName: "영동고속도로",
    locationName: "강릉JC",
    analysisSummary: "분석 요청이 접수되었으며 AI 서버 처리 대기 중입니다.",
  },
  {
    id: "rep-004",
    reportCode: "RPT-20260429-004",
    title: "중부선 정차 의심 오탐 검토",
    reportType: "LANE_STOP_REPORT",
    purpose: "TEST_DEMO",
    reporter: "최관리",
    location: "중부고속도로 대전JC",
    cctvId: "cctv-004",
    analysisStatus: "FAILED",
    status: "REJECTED",
    priority: "LOW",
    createdAt: "2026-04-29 10:18:00",
    attachmentName: "daejeon_review.mp4",
    attachmentType: "video",
    uploadedAt: "2026-04-29 10:17:40",
    roadName: "중부고속도로",
    locationName: "대전JC",
    analysisSummary: "영상 품질 문제로 분석이 실패했습니다.",
  },
  {
    id: "rep-005",
    reportCode: "RPT-20260429-005",
    title: "호남선 갓길 차량 확인 요청",
    reportType: "SHOULDER_STOP_REPORT",
    purpose: "REPORT",
    reporter: "정관제",
    location: "호남고속도로 광주JC",
    cctvId: "cctv-008",
    analysisStatus: "WAITING",
    status: "SUBMITTED",
    priority: "HIGH",
    createdAt: "2026-04-29 10:31:00",
    attachmentName: "gwangju_shoulder.jpg",
    attachmentType: "image",
    uploadedAt: "2026-04-29 10:30:38",
    roadName: "호남고속도로",
    locationName: "광주JC",
    analysisSummary: "등록 완료 후 분석 요청 전 상태입니다.",
  },
];
