import type { Incident } from "./types";

export const mockIncidents: Incident[] = [
  {
    id: "inc-001",
    code: "STP-20260429-001",
    eventType: "LANE_STOP",
    location: "경부고속도로 수원IC 123.4K 주행차로",
    riskLevel: "CRITICAL",
    riskScore: 91,
    confidence: 0.942,
    stoppedDurationSec: 72,
    status: "REVIEWING",
    detectedAt: "2026-04-29 09:12:30",
    cctvId: "cctv-001",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "LANE",
    movementDeltaPx: 1.8,
    memo: "1차로 정차 지속. 후속 차량 감속 확인.",
    its: { weather: "맑음", trafficVolume: "혼잡", nearestPatrolEta: "8분" },
  },
  {
    id: "inc-002",
    code: "STP-20260429-002",
    eventType: "SHOULDER_STOP",
    location: "영동고속도로 용인IC 45.1K 갓길",
    riskLevel: "MEDIUM",
    riskScore: 58,
    confidence: 0.887,
    stoppedDurationSec: 135,
    status: "IN_PROGRESS",
    detectedAt: "2026-04-29 09:04:10",
    cctvId: "cctv-002",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "SHOULDER",
    movementDeltaPx: 2.2,
    memo: "갓길 정차. 비상등 점등 여부 확인 필요.",
    its: { weather: "흐림", trafficVolume: "원활", nearestPatrolEta: "14분" },
  },
  {
    id: "inc-003",
    code: "STP-20260429-003",
    eventType: "LANE_STOP",
    location: "서해안고속도로 매송IC 18.6K 주행차로",
    riskLevel: "HIGH",
    riskScore: 77,
    confidence: 0.915,
    stoppedDurationSec: 49,
    status: "DETECTED",
    detectedAt: "2026-04-29 08:52:44",
    cctvId: "cctv-003",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "LANE",
    movementDeltaPx: 3.1,
    its: { weather: "비", trafficVolume: "서행", nearestPatrolEta: "11분" },
  },
  {
    id: "inc-004",
    code: "STP-20260428-011",
    eventType: "SHOULDER_STOP",
    location: "중부고속도로 대소JC 201.2K 갓길",
    riskLevel: "LOW",
    riskScore: 34,
    confidence: 0.834,
    stoppedDurationSec: 240,
    status: "RESOLVED",
    detectedAt: "2026-04-28 18:11:02",
    cctvId: "cctv-004",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "SHOULDER",
    movementDeltaPx: 1.2,
    its: { weather: "맑음", trafficVolume: "원활", nearestPatrolEta: "처리완료" },
  },
];

export const futureFeatures = ["낙하물", "보행자 진입", "역주행 의심", "사고 의심"];
