import type { Incident } from "./types";

export const mockIncidents: Incident[] = [
  {
    id: "inc-001",
    code: "STP-20260429-001",
    title: "수원IC 1차로 정차 차량",
    eventType: "LANE_STOP",
    roadName: "경부고속도로",
    location: "경부고속도로 수원IC 123.4K 주행차로",
    riskLevel: "CRITICAL",
    riskScore: 91,
    confidence: 0.942,
    stoppedDurationSec: 72,
    status: "REVIEWING",
    detectedAt: "2026-04-29 09:12:30",
    assignee: "김관제",
    cctvId: "cctv-001",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "LANE",
    movementDeltaPx: 1.8,
    memo: "1차로 정차 지속. 후속 차량 감속 확인.",
    its: { weather: "맑음", trafficVolume: "혼잡", nearestPatrolEta: "8분" },
  },
  {
    id: "inc-002",
    code: "STP-20260429-002",
    title: "용인IC 갓길 장기 정차",
    eventType: "SHOULDER_STOP",
    roadName: "영동고속도로",
    location: "영동고속도로 용인IC 45.1K 갓길",
    riskLevel: "MEDIUM",
    riskScore: 58,
    confidence: 0.887,
    stoppedDurationSec: 135,
    status: "ASSIGNED",
    detectedAt: "2026-04-29 09:04:10",
    assignee: "박순찰",
    cctvId: "cctv-002",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "SHOULDER",
    movementDeltaPx: 2.2,
    memo: "갓길 정차. 비상등 점등 여부 확인 필요.",
    its: { weather: "흐림", trafficVolume: "원활", nearestPatrolEta: "14분" },
  },
  {
    id: "inc-003",
    code: "STP-20260429-003",
    title: "매송IC 주행차로 정차 의심",
    eventType: "LANE_STOP",
    roadName: "서해안고속도로",
    location: "서해안고속도로 매송IC 18.6K 주행차로",
    riskLevel: "HIGH",
    riskScore: 77,
    confidence: 0.915,
    stoppedDurationSec: 49,
    status: "DETECTED",
    detectedAt: "2026-04-29 08:52:44",
    assignee: "미배정",
    cctvId: "cctv-003",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "LANE",
    movementDeltaPx: 3.1,
    its: { weather: "비", trafficVolume: "서행", nearestPatrolEta: "11분" },
  },
  {
    id: "inc-004",
    code: "STP-20260428-011",
    title: "대소JC 갓길 정차 처리 완료",
    eventType: "SHOULDER_STOP",
    roadName: "중부고속도로",
    location: "중부고속도로 대소JC 201.2K 갓길",
    riskLevel: "LOW",
    riskScore: 34,
    confidence: 0.834,
    stoppedDurationSec: 240,
    status: "RESOLVED",
    detectedAt: "2026-04-28 18:11:02",
    assignee: "이관제",
    cctvId: "cctv-004",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "SHOULDER",
    movementDeltaPx: 1.2,
    its: { weather: "맑음", trafficVolume: "원활", nearestPatrolEta: "처리완료" },
  },
  {
    id: "inc-005",
    code: "STP-20260429-004",
    title: "안산IC 갓길 정차 오탐 검토",
    eventType: "SHOULDER_STOP",
    roadName: "서해안고속도로",
    location: "서해안고속도로 안산IC 81.2K 갓길",
    riskLevel: "LOW",
    riskScore: 22,
    confidence: 0.621,
    stoppedDurationSec: 38,
    status: "FALSE_POSITIVE",
    detectedAt: "2026-04-29 10:03:18",
    assignee: "최관리",
    cctvId: "cctv-002",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "SHOULDER",
    movementDeltaPx: 5.8,
    memo: "저속 이동 차량으로 확인.",
    its: { weather: "맑음", trafficVolume: "원활", nearestPatrolEta: "오탐종료" },
  },
  {
    id: "inc-006",
    code: "STP-20260429-005",
    title: "천안IC 주행차로 정차 종결",
    eventType: "LANE_STOP",
    roadName: "경부고속도로",
    location: "경부고속도로 천안IC 152.0K 주행차로",
    riskLevel: "MEDIUM",
    riskScore: 49,
    confidence: 0.801,
    stoppedDurationSec: 92,
    status: "CLOSED",
    detectedAt: "2026-04-29 07:55:22",
    assignee: "정대응",
    cctvId: "cctv-006",
    snapshotUrl: "/assets/images/hero-piano-road.png",
    roiType: "LANE",
    movementDeltaPx: 2.6,
    memo: "상황 종료 및 이력 종결.",
    its: { weather: "흐림", trafficVolume: "서행", nearestPatrolEta: "종결" },
  },
];

export const futureFeatures = ["낙하물", "보행자 진입", "역주행 의심", "사고 의심"];
