import type { LlmModelMetadata, LlmReport, LlmTrainingDataset, LlmTrainingSummary } from "./types";

export const mockLlmTrainingSummary: LlmTrainingSummary = {
  totalSampleCount: 18420,
  latestCreatedAt: "2026-04-29 08:40:00",
  trainingVersion: "train-v2026.04.29",
  modelStatus: "READY",
};

export const mockLlmTrainingDatasets: LlmTrainingDataset[] = [
  {
    id: "dataset-report-20260429",
    datasetName: "incident-report-draft-ko",
    purpose: "REPORT",
    sampleCount: 6420,
    version: "report-v1.8.0",
    status: "READY",
    createdAt: "2026-04-29 08:40:00",
  },
  {
    id: "dataset-chatbot-20260428",
    datasetName: "incident-response-chatbot-ko",
    purpose: "CHATBOT",
    sampleCount: 5180,
    version: "chatbot-v1.5.2",
    status: "VALIDATING",
    createdAt: "2026-04-28 21:10:00",
  },
  {
    id: "dataset-risk-20260427",
    datasetName: "risk-context-summary-ko",
    purpose: "RISK_SUMMARY",
    sampleCount: 3920,
    version: "risk-v1.3.1",
    status: "READY",
    createdAt: "2026-04-27 19:35:00",
  },
  {
    id: "dataset-alert-20260426",
    datasetName: "operator-alert-template-ko",
    purpose: "ALERT",
    sampleCount: 2900,
    version: "alert-v1.2.0",
    status: "ARCHIVED",
    createdAt: "2026-04-26 17:20:00",
  },
];

export const mockLlmModelMetadata: LlmModelMetadata = {
  provider: "MOCK",
  modelName: "staccato-incident-assistant",
  promptVersion: "prompt-v2026.04",
  fallbackEnabled: true,
};

export const mockLlmReports: LlmReport[] = [
  {
    id: "llm-001",
    incidentId: "inc-001",
    incidentCode: "STP-20260429-001",
    reportTitle: "수원IC 주행차로 정차 긴급 대응 보고서",
    reportType: "INCIDENT_REPORT",
    generationStatus: "DRAFT",
    llmProvider: "MOCK",
    llmModel: "mock-incident-writer",
    generatedBy: "김관제",
    generatedAt: "2026-04-29 09:16:00",
    draft:
      "경부고속도로 수원IC 123.4K 주행차로에서 정차 차량이 탐지되었습니다. AI 신뢰도는 94.2%이며 정차 지속 시간은 72초입니다. 위험도는 긴급으로 분류되어 관제 확인과 현장 출동 요청이 필요합니다.",
    verified: false,
    updatedAt: "2026-04-29 09:16:00",
    sections: {
      overview: "주행차로 내 정차 차량이 AI에 의해 탐지되었습니다.",
      location: "경부고속도로 수원IC 123.4K 주행차로",
      aiDetection: "AI 신뢰도 94.2%, 정차 지속 시간 72초",
      riskAssessment: "후속 차량 추돌 위험이 높아 CRITICAL로 분류",
      currentStatus: "관제 검토 중",
      requiredActions: "CCTV 확대 확인, 순찰 출동 요청, 사고 대응 채팅방 상황 공유",
    },
  },
  {
    id: "llm-002",
    incidentId: "inc-002",
    incidentCode: "STP-20260429-002",
    reportTitle: "용인IC 갓길 장기 정차 요약",
    reportType: "INCIDENT_SUMMARY",
    generationStatus: "EDITED",
    llmProvider: "MOCK",
    llmModel: "mock-incident-writer",
    generatedBy: "박운영",
    generatedAt: "2026-04-29 09:22:00",
    draft:
      "영동고속도로 용인IC 45.1K 갓길에서 장기 정차 차량이 확인되었습니다. 위험도는 보통이며 운전자 안전 확인이 필요합니다.",
    verified: false,
    updatedAt: "2026-04-29 09:28:00",
    sections: {
      overview: "갓길 정차 차량이 일정 시간 이상 움직임 없이 유지되었습니다.",
      location: "영동고속도로 용인IC 45.1K 갓길",
      aiDetection: "AI 신뢰도 88.7%, 정차 지속 시간 135초",
      riskAssessment: "갓길 위치로 즉시 충돌 위험은 낮으나 장기 정차로 안전 확인 필요",
      currentStatus: "담당 배정",
      requiredActions: "비상등 여부 확인, 순찰 ETA 공유, 필요 시 견인 지원 요청",
    },
  },
  {
    id: "llm-003",
    incidentId: "inc-003",
    incidentCode: "STP-20260429-003",
    reportTitle: "매송IC 주행차로 정차 요약 생성 중",
    reportType: "INCIDENT_SUMMARY",
    generationStatus: "GENERATING",
    llmProvider: "MOCK",
    llmModel: "mock-incident-writer",
    generatedBy: "이상황",
    generatedAt: "2026-04-29 09:01:00",
    draft: "보고서 생성 중입니다.",
    verified: false,
    updatedAt: "2026-04-29 09:01:00",
    sections: {
      overview: "생성 중",
      location: "서해안고속도로 매송IC 18.6K 주행차로",
      aiDetection: "AI 분석 결과를 보고서로 변환 중",
      riskAssessment: "생성 중",
      currentStatus: "탐지됨",
      requiredActions: "생성 완료 후 관리자 검토 필요",
    },
  },
  {
    id: "llm-004",
    incidentId: "inc-004",
    incidentCode: "STP-20260428-011",
    reportTitle: "대소JC 처리 완료 보고서",
    reportType: "INCIDENT_REPORT",
    generationStatus: "CONFIRMED",
    llmProvider: "MOCK",
    llmModel: "mock-incident-writer",
    generatedBy: "정대응",
    generatedAt: "2026-04-28 18:40:00",
    draft: "중부고속도로 대소JC 갓길 정차 건은 현장 확인 후 처리 완료되었습니다.",
    verified: true,
    updatedAt: "2026-04-28 18:45:00",
    sections: {
      overview: "갓길 정차 건 처리 완료",
      location: "중부고속도로 대소JC 201.2K 갓길",
      aiDetection: "AI 신뢰도 83.4%",
      riskAssessment: "LOW, 갓길 위치로 직접 위험 낮음",
      currentStatus: "처리완료",
      requiredActions: "이력 보관 및 재발 여부 모니터링",
    },
  },
];
