/**
 * 파일 역할: CCTV 화면을 백엔드 없이도 구성하거나 응답 누락을 보완할 때 사용하는 예시 데이터입니다.
 * 유지보수 참고: 실제 API 계약과 같은 타입을 유지해 개발용 데이터가 운영 코드의 가정을 왜곡하지 않도록 합니다.
 */
import type { Cctv } from "./types";

// 코드 설명: mockCctvs 값을 선언해 이후 계산, 조건 판단 또는 화면 렌더링에서 재사용합니다.
export const mockCctvs: Cctv[] = [
  {
    id: "cctv-001",
    cctvCode: "CCTV-01",
    name: "수원IC",
    road: "경부고속도로",
    roadName: "경부고속도로",
    location: "경기도 수원시",
    locationName: "수원IC",
    direction: "서울방향",
    status: "ONLINE",
    isLive: true,
    isAiDetected: true,
    detectionType: "tire",
    confidence: 0.87,
    lastUpdatedAt: "2026-04-28 10:23:15",
    roiTypes: ["LANE", "SHOULDER"],
  },
  {
    id: "cctv-002",
    cctvCode: "CCTV-02",
    name: "안산IC",
    road: "서해안고속도로",
    roadName: "서해안고속도로",
    location: "경기도 안산시",
    locationName: "안산IC",
    direction: "목포방향",
    status: "ONLINE",
    isLive: true,
    isAiDetected: false,
    lastUpdatedAt: "2026-04-28 10:22:45",
    roiTypes: ["LANE", "SHOULDER"],
  },
  {
    id: "cctv-003",
    cctvCode: "CCTV-03",
    name: "강릉JC",
    road: "영동고속도로",
    roadName: "영동고속도로",
    location: "강원도 강릉시",
    locationName: "강릉JC",
    direction: "강릉방향",
    status: "OFFLINE",
    isLive: true,
    isAiDetected: false,
    lastUpdatedAt: "2026-04-28 09:45:00",
    roiTypes: ["LANE"],
  },
  {
    id: "cctv-004",
    cctvCode: "CCTV-04",
    name: "대전JC",
    road: "중부고속도로",
    roadName: "중부고속도로",
    location: "대전광역시",
    locationName: "대전JC",
    direction: "하남방향",
    status: "ONLINE",
    isLive: true,
    isAiDetected: true,
    detectionType: "stopped_vehicle",
    confidence: 0.92,
    lastUpdatedAt: "2026-04-28 10:20:30",
    roiTypes: ["LANE", "SHOULDER"],
  },
  {
    id: "cctv-005",
    cctvCode: "CCTV-05",
    name: "마산IC",
    road: "남해고속도로",
    roadName: "남해고속도로",
    location: "경상남도 창원시",
    locationName: "마산IC",
    direction: "부산방향",
    status: "MAINTENANCE",
    isLive: true,
    isAiDetected: false,
    lastUpdatedAt: "2026-04-28 08:00:00",
    roiTypes: ["SHOULDER"],
  },
  {
    id: "cctv-006",
    cctvCode: "CCTV-06",
    name: "천안IC",
    road: "경부고속도로",
    roadName: "경부고속도로",
    location: "충청남도 천안시",
    locationName: "천안IC",
    direction: "부산방향",
    status: "ONLINE",
    isLive: true,
    isAiDetected: false,
    lastUpdatedAt: "2026-04-28 10:21:00",
    roiTypes: ["LANE"],
  },
  {
    id: "cctv-007",
    cctvCode: "CCTV-07",
    name: "평택JC",
    road: "서해안고속도로",
    roadName: "서해안고속도로",
    location: "경기도 평택시",
    locationName: "평택JC",
    direction: "서울방향",
    status: "ONLINE",
    isLive: true,
    isAiDetected: true,
    detectionType: "pedestrian",
    confidence: 0.95,
    lastUpdatedAt: "2026-04-28 10:18:45",
    roiTypes: ["LANE"],
  },
  {
    id: "cctv-008",
    cctvCode: "CCTV-08",
    name: "광주JC",
    road: "호남고속도로",
    roadName: "호남고속도로",
    location: "광주광역시",
    locationName: "광주JC",
    direction: "순천방향",
    status: "ONLINE",
    isLive: true,
    isAiDetected: false,
    lastUpdatedAt: "2026-04-28 10:19:30",
    roiTypes: ["LANE", "SHOULDER"],
  },
];
