services:
  ai-server:
    build:
      context: ./ai-server
    container_name: staccato-ai-server
    ports:
      - "8001:8001"
    volumes:
      - ./ai-server/storage:/app/storage
    restart: unless-stopped

  llm-server:
    build:
      context: ./llm-server
    container_name: staccato-llm-server
    ports:
      - "8000:8000"
    volumes:
      - ./llm-server/storage:/app/storage
    restart: unless-stopped
