services:
  ai-server:
    build:
      context: ./ai-server
    container_name: staccato-ai-server
    ports:
      - "8001:8001"
    volumes:
      - ./ai-server/storage:/app/storage
    restart: unless-stopped

